#pragma once

//#define POINTER_DEFINE
//#define POINTER_MEM_OCCUPY
//#define NULL_POINTER
//#define DANGLING_POINTER


//#define CONST_DECORATE_POINTER

//#define POINTER_AND_ARRAY
//#define POINTER_AND_FUNCTION
#define POINTER_ARRAY_FUNCTION