#pragma once


#include <iostream>
using namespace std;


//#define CLASS_ENCAPSULATION
//#define CLASS_ACCESS_PRIVILEGE
//#define STRUCT_CLASS_DIFF
//#define CONSTRUCT_DESTRUCTOR_FUNCTION
//#define CONSTRUCT_FUNCTION_TYPE_CALLED
//#define COPY_CONSTRUCT_CALLED_TIME
//#define CONSTRUCT_CALL_PRINCIPLE
//#define DEEP_SHALLOW_COPY
//#define INIT_LIST
//#define CLASS_OBJ_AS_CLASS_FIELD
//#define STATIC_FIELD_METHOD
//#define FIELD_METHOD_DIFF_STORAGE

//#define THIS_POINTER

#define CONST_CLASS_METHOD