#pragma once

//#define CLASS_ENCAPSULATION

//#define CLASS_INHERITANCE

//#define CLASS_POLYMORPHISM

//#define CLASS_ACCESS_PRIVILEGE

//#define STRUCT_CLASS_DIFF

//#define CONSTRUCT_DESTRUCTOR_FUNCTION

#define CONSTRUCT_FUNCTION_TYPE_CALLED