#pragma once

#include <iostream>
using namespace std;

//#define FUNCTION_TEMPLATE

//#define ORDINARY_FUNCTION_TEMPLATE

//#define ORDINARY_TEMPLATE_FUNCTION_CALLED

//#define TEMPLATE_LIMITATION

//#define CLASS_TEMPLATE
//#define CLASS_TEMPLATE_DEFAULT_PARAMS
//#define CLASS_TEMPLATE_FUNCTION_CREATE_TIME

//#define CLASS_TEMPLATE_AS_FUNCTION_PARAM
//#define CLASS_TEMPLATE_EXTEND

//#define CLASS_TEMPLATE_METHOD_OUTSIDE

//#define CLASS_TEMPLATE_SPLIT_MULTIL_FILE_1
//#define CLASS_TEMPLATE_SPLIT_MULTIL_FILE_2

//#define CLASS_TEMPLATE_FRIEND

#define CLASS_TEMPLATE_SAMPLE